name: MyHome.NG CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, json, curl, dom, sqlite3
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-dev

    - name: Prepare Laravel application
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Set database environment variables for SQLite
      run: |
        echo DB_CONNECTION=sqlite >> .env
        echo DB_DATABASE=/tmp/database.sqlite >> .env

    - name: Create SQLite database file
      run: touch /tmp/database.sqlite

    - name: Display .env file
      run: cat .env

    - name: Clear and cache Laravel configuration
      run: php artisan config:clear && php artisan config:cache

    - name: Run migrations
      run: php artisan migrate --force

    - name: Install Laravel Passport
      run: php artisan passport:install --force

    - name: Run tests
      run: vendor/bin/phpunit

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-dev

    - name: Prepare Laravel application
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache
        php artisan route:cache
        php artisan view:clear
        php artisan cache:clear

    - name: Set database environment variables for SQLite
      run: |
        echo DB_CONNECTION=sqlite >> .env
        echo DB_DATABASE=/tmp/database.sqlite >> .env

    - name: Create SQLite database file
      run: touch /tmp/database.sqlite

    - name: Clear and cache Laravel configuration
      run: php artisan config:clear && php artisan config:cache

    - name: Run migrations
      run: php artisan migrate --force

    - name: Install Laravel Passport
      run: php artisan passport:install --force

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-your-service-id" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -d ''
