name: MyHome.NG CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, bcmath, json, curl, dom, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-dev

    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install -y mysql-client
        until mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
          echo waiting for mysql
          sleep 2
        done

    - name: Prepare Laravel application
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache

    - name: Set environment variables
      run: |
        echo DB_CONNECTION=mysql >> .env
        echo DB_HOST=127.0.0.1 >> .env
        echo DB_PORT=3306 >> .env
        echo DB_DATABASE=test_db >> .env
        echo DB_USERNAME=root >> .env
        echo DB_PASSWORD=password >> .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-dev

    - name: Prepare Laravel application
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache
        php artisan route:cache
        php artisan view:clear
        php artisan cache:clear
        php artisan migrate --force

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-your-service-id" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -d ''
